[project]
name = "Crankpy PyScript CLI Test"
description = "Testing Crankpy compatibility with PyScript CLI"
version = "0.1.0"
author = "Test Author"
email = "test@example.com"

[js_modules.main]
"https://cdn.jsdelivr.net/npm/@b9g/crank@0.7.1/+esm" = "crank_core"

[[fetch]]
files = ["../crank/__init__.py", "../crank/dom.py", "../crank/html.py", "../crank/async.py"]
to_folder = "crank"